disabled_rules: # rule identifiers to exclude from running
#
opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping
  - identifier_name
  - trailing_whitespace
  - type_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - unused_import
  - anyobject_protocol
  - closure_body_length
  - closure_end_indentation
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - implicitly_unwrapped_optional
  - control_statement
  - switch_case_on_newline
  - switch_case_alignment
  # Find all the available rules by running:
  # swiftlint rules
# included: # paths to include during linting. `--path` is ignored if present.
#   - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - PhiModule/.build

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: error # explicitly
force_unwrapping:
  severity: error
implicitly_unwrapped_optional:
  severity: error
control_statement:
  severity: error
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 200
# they can set both implicitly with an array

type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200

large_tuple:
   - 3 # warning

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
  excluded: # excluded via string array
    - id
    - URL
    - url
    - get
    - put
    - api
    - API
    - Env
    - env
    - GlobalAPIKey
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - to
    - id
    - ok
    - of
    - no
    - URL
    - url
    - get
    - put
    - api
    - API
    - Env
    - env
    - GlobalAPIKey
reporter: "xcode" 